In [4]:
import torch
print("Is CUDA ready?", torch.cuda.is_available())

Is CUDA ready? True


In [5]:
x = torch.rand(3, 3)
print(x)

tensor([[0.2237, 0.7071, 0.6066],
        [0.4947, 0.7202, 0.3660],
        [0.2304, 0.3357, 0.7004]])


In [7]:
y = torch.ones_like(x, device="cuda")
x = x.to("cuda")

z = x + y
print(z)

tensor([[1.2237, 1.7071, 1.6066],
        [1.4947, 1.7202, 1.3660],
        [1.2304, 1.3357, 1.7004]], device='cuda:0')


In [8]:
z = z.to("cpu")
print(z)

tensor([[1.2237, 1.7071, 1.6066],
        [1.4947, 1.7202, 1.3660],
        [1.2304, 1.3357, 1.7004]])


In [9]:
s = 10000
device = "cpu"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)

%time z = torch.matmul(x, y)

CPU times: user 11.2 s, sys: 142 ms, total: 11.3 s
Wall time: 6.12 s


In [10]:
s = 10000
device = "cuda"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)
torch.cuda.synchronize()

%time z = torch.matmul(x, y); torch.cuda.synchronize()

CPU times: user 529 ms, sys: 308 ms, total: 837 ms
Wall time: 16.7 s
